# Generated by Erlang.mk. Edit at your own risk!

src/astar.erl:: include/common.hrl include/schema.hrl; @touch $@
src/combat.erl:: include/common.hrl include/schema.hrl; @touch $@
src/counter.erl:: include/schema.hrl; @touch $@
src/db.erl:: include/common.hrl include/schema.hrl; @touch $@
src/effect.erl:: include/common.hrl include/schema.hrl; @touch $@
src/encounter.erl:: include/common.hrl include/schema.hrl; @touch $@
src/game.erl:: include/common.hrl include/schema.hrl; @touch $@
src/game_loop.erl:: include/common.hrl include/schema.hrl; @touch $@
src/htn.erl:: include/common.hrl include/schema.hrl; @touch $@
src/item.erl:: include/schema.hrl; @touch $@
src/item_attr.erl:: include/schema.hrl; @touch $@
src/item_def.erl:: include/schema.hrl; @touch $@
src/login.erl:: include/common.hrl include/schema.hrl; @touch $@
src/magic.erl:: include/common.hrl include/schema.hrl; @touch $@
src/map.erl:: include/common.hrl include/schema.hrl; @touch $@
src/message.erl:: include/schema.hrl; @touch $@
src/npc.erl:: include/common.hrl include/schema.hrl; @touch $@
src/obj.erl:: include/common.hrl include/schema.hrl; @touch $@
src/obj_attr.erl:: include/schema.hrl; @touch $@
src/obj_template.erl:: include/schema.hrl; @touch $@
src/perception.erl:: include/common.hrl include/schema.hrl; @touch $@
src/player.erl:: include/common.hrl include/schema.hrl; @touch $@
src/recipe.erl:: include/schema.hrl; @touch $@
src/recipe_def.erl:: include/schema.hrl; @touch $@
src/resource.erl:: include/common.hrl include/schema.hrl; @touch $@
src/resource_def.erl:: include/schema.hrl; @touch $@
src/revent.erl:: include/schema.hrl; @touch $@
src/setup.erl:: include/common.hrl include/schema.hrl; @touch $@
src/skill.erl:: include/common.hrl include/schema.hrl; @touch $@
src/skill_attr.erl:: include/schema.hrl; @touch $@
src/skill_def.erl:: include/schema.hrl; @touch $@
src/sound.erl:: include/common.hrl include/schema.hrl; @touch $@
src/sp_app.erl:: include/common.hrl include/schema.hrl; @touch $@
src/structure.erl:: include/common.hrl include/schema.hrl; @touch $@
src/util.erl:: include/common.hrl include/schema.hrl; @touch $@
src/villager.erl:: include/common.hrl include/schema.hrl; @touch $@

COMPILE_FIRST +=
